/* tslint:disable */
/* eslint-disable */
/**
 * API
 * internal_api
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateParams
 */
export interface CreateParams {
    /**
     * user name
     * @type {string}
     * @memberof CreateParams
     */
    name: string;
    /**
     * user status
     * @type {number}
     * @memberof CreateParams
     */
    status: CreateParamsStatus;
    /**
     * user posts
     * @type {Array<{ [key: string]: string | undefined; }>}
     * @memberof CreateParams
     */
    user_posts: Array<{ [key: string]: string | undefined; }>;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateParamsStatus {
    NUMBER_0 = 0,
    NUMBER_1 = 1
}



